### ISSUE TITLE
Help with page loading needed

### ISSUE THREAD

**Issue by kanalasumant** [BuildingXwithJS/puppeteer-examples#1]
Hey Tim, great tutorial explaining the basic concepts of Puppeteer. I'm trying to simulate a page load and scrape some data from [this](http://reasonmlhub.com/exploring-reasonml/toc.html) site and this is the following script I came up with. But whatever I do, the script is returning an empty object.

```
'use strict';
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('http://reasonmlhub.com/exploring-reasonml/toc.html', { 
    waitLoad: true, 
    waitNetworkIdle: true
  });
  const mainNav = '#TOC';
  await page.waitForSelector(mainNav);
  const mainNavSelector = await page.evaluate(mainNav => {
    return document.querySelector(mainNav);
  }, mainNav);
  console.log(mainNavSelector);
  // await page.pdf({
  //   path: 'ReasonML-Dr.Axel.pdf',
  //   format: 'letter'
  // });

  await browser.close();
})();
```

I tried page.goto without options, but still the same result. Any suggestions on this is appreciated.

**Comment by yamalight** [comment]
@kanalasumant I don't think `eval()` can return complex objects. Have you tried returning e.g. `document.querySelector(mainNav).innerHTML`?

**Comment by kanalasumant** [comment]
It works. Thanks! Much appreciated.
